use_frameworks!

platform :ios, '9.0'

target 'NSwippableCell_Example' do
  pod 'NSwippableCell', :path => '../'

  target 'NSwippableCell_Tests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.1'

  end
end
